name: Deploy static content to Pages

on:
  push:
    branches:
      - production
      - development
  pull_request:
    branches:
      - production
      - development

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  format:
    name: JS Code Format
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: pycon-website
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '20.11'
      - name: Install node dependencies
        run: |
          cd pycon-website/
          npm install
      - name: Show node environment
        run: |
          node --version
          npm --version
      - name: Run JS lint
        run: |
          cd pycon-website/
          npm run lint-only

  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    name: Deploy to Production
    needs: format
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    # needs: format

    steps:
      - name: Generate access token
        if: always()
        id: generate_access_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PYCON_CO_APP_ID }}
          private-key: ${{ secrets.PYCON_CO_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Clone target repository
        run: |
          echo ${{github.event_name }}
          echo ${{ github.base_ref }}
          git clone https://git:'${{steps.generate_access_token.outputs.token}}'@github.com/PyConColombia/website-develop website-develop
          rm -rf website-develop/dist/
          mv dist/ website-develop/dist/
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
      - name: Commit and push changes
        run: |
          cd website-develop
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages
